name: Spartan
author: Evangelos Dedes @Vagdedes
main: com.vagdedes.spartan.Register
version: Phase 534
website: https://www.idealistic.ai
description: In the mission to create & maintain the best Minecraft anti-cheat, powered by Machine Learning.
api-version: 1.13
softdepend: [mcMMO, ProtocolSupport, VeinMiner, AcidRain, AcidIsland, EcoEnchants, CustomEnchantsPlus,
             aSkyBlock, AdvancedAbilities, CrackShot, CrackShotPlus, CraftBook, GrapplingHook, ProtocolLib,
             MagicSpells, MineBomb, MineTinker, MythicMobs, PrinterMode, ProjectKorra, RealDualWield,
             SmashHit, SuperPickaxe, TreeFeller, Vehicles, WildTools, Geyser-Spigot, floodgate-bukkit,
             FileGUI]
load: POSTWORLD
folia-supported: true
commands:
  spartan: