name: Spartan
authors: [Evangelos Dedes @Vagdedes, pawsashatoy]
main: com.vagdedes.spartan.Register
version: Phase 536.3
website: https://www.vagdedes.com
description: In the mission to create & maintain the best Minecraft anti-cheat, powered by Machine Learning.
api-version: 1.13
softdepend: [mcMMO, ProtocolSupport, VeinMiner, AcidRain, AcidIsland, EcoEnchants, CustomEnchantsPlus,
             aSkyBlock, AdvancedAbilities, CrackShot, CrackShotPlus, CraftBook, GrapplingHook, ProtocolLib,
             MagicSpells, MineBomb, MineTinker, MythicMobs, PrinterMode, ProjectKorra, RealDualWield,
             SuperPickaxe, TreeFeller, Vehicles, WildTools, floodgate-bukkit, FileGUI]
load: POSTWORLD
folia-supported: true
commands:
  spartan: